name: digits
channels:
  - damianavila82
  - satra
  - menpo
  - pluraldatum
  - glemaitre
  - soumith
  - conda-forge
  - defaults
  - simpleitk
dependencies:
  - python>=3.6,<3.7.0
  - tensorflow=>1.2.0,<1.3.0
  - Pillow>=2.3.0,<=3.1.2
  - numpy>=1.8.1,<=1.14.0
  - scipy
  - protobuf>=2.5.0,<=3.2.0
  - gevent
  - gevent-websocket
  - lmdb
  - python-lmdb
  - h5py>=2.2.1,<=2.6.0
  - pydot
  - matplotlib
  - scikit-fmm>=0.0.9
  - graphviz
  - opencv3>=3.0
  - pip:
    - Flask==0.10.1
    - Flask-WTF>=0.11,<=0.12
    - wtforms>=2.0,<=2.1
    - Flask-SocketIO==2.6
    - six
    - requests
    - boto>=2.48.0
    - python-magic>=0.2
    - psutil

