name: digits
channels:
  - damianavila82
  - satra
  - menpo
  - pluraldatum
  - glemaitre
  - soumith
  - conda-forge
  - defaults
  - simpleitk
dependencies:
  - python=3.6
  - tensorflow==1.2.0
  - Pillow>=2.3.0,<=3.1.2
  - numpy>=1.8.1,<=1.14.0
  - scipy
  - protobuf>=2.5.0,<=3.2.0
  - gevent>=1.0,<=1.1.0
  - gevent-websocket==0.9.3
  - lmdb
  - python-lmdb
  - h5py>=2.2.1,<=2.6.0
  - pydot>=1.0.28,<=1.0.29
  - matplotlib
  - scikit-fmm>=0.0.9
  - graphviz
  - opencv3>=3.0
  - pip:
    - Flask==0.10.1
    - Flask-WTF>=0.11,<=0.12
    - wtforms>=2.0,<=2.1
    - Flask-SocketIO==2.6
    - six>=1.5.2,<=1.10.0
    - requests>=2.2.1,<=2.9.1
    - boto>=2.48.0
    - python-magic>=0.2
    - psutil>=1.2.1,<=3.4.2

